#!/usr/bin/env python
#-*-coding:utf-8 -*-
__author__ = 'jiang'
# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# join.py
# Created on: 2016-12-30 10:27:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module

import arcpy
arcpy.env.workspace = "D:/preset/培训素材/广州培训/地图制图数据/GIS基础/广州数据.gdb"
#行政区__2_ = "行政区"
Export_Output = "C:/Users/Esri/Desktop/Export_Output.dbf"
arcpy.JoinField_management("行政区", "NAME", Export_Output, "名称", "人口2005;人口2014")