# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ddd.py
# Created on: 2016-09-19 17:51:07.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
CODE1_gdb__2_ = "C:\\Users\\Esri\\Desktop\\test__20160919\\投影前\\CODE1.gdb"
HYDA_1 = "C:\\Users\\Esri\\Desktop\\test__20160919\\投影前\\CODE1.gdb\\RESP_1"
v_name_ = "C:\\Users\\Esri\\Desktop\\test__20160919\\投影后\\CODE1.gdb\\%name%"
Name = "RESP_1"
CODE1_gdb = "C:\\Users\\Esri\\Desktop\\test__20160919\\投影前\\CODE1.gdb"

# Process: Iterate Feature Classes
arcpy.IterateFeatureClasses_mb(CODE1_gdb__2_, "", "", "NOT_RECURSIVE")

# Process: Project
arcpy.Project_management(HYDA_1, v_name_, "PROJCS['CGCS2000_GK_CM_117E',GEOGCS['GCS_China_Geodetic_Coordinate_System_2000',DATUM['D_China_2000',SPHEROID['CGCS2000',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Gauss_Kruger'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',117.0],PARAMETER['Scale_Factor',1.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "GEOGCS['GCS_China_Geodetic_Coordinate_System_2000',DATUM['D_China_2000',SPHEROID['CGCS2000',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

